apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: php-apache
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: php-apache-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        resources:
           requests:
              cpu: "200m"

        ports:
        - containerPort: 80

