apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-tomcat
  labels:
    app: nginx-tomcat
spec:
  containers:
      - name: container-nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
      - name: container-tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
